export const GET_ALL_NEWS_REQUEST = 'GET_ALL_NEWS_REQUEST';
export const GET_ALL_NEWS_SUCCESS = 'GET_ALL_NEWS_SUCCESS';
export const GET_ALL_NEWS_FAIL = 'GET_ALL_NEWS_FAIL';

export const GET_POSTER_REQUEST = "GET_POSTER_REQUEST"
export const GET_POSTER_SUCCESS = "GET_POSTER_SUCCESS"
export const GET_POSTER_FAIL = "GET_POSTER_FAIL"

export const ADD_NEW_NEWS_REQUEST = "ADD_NEW_NEWS_REQUEST"
export const ADD_NEW_NEWS_SUCCESS = "ADD_NEW_NEWS_SUCCESS"
export const ADD_NEW_NEWS_FAIL = "ADD_NEW_NEWS_FAIL"