export const GET_ALL_RULES_REQUEST = "GET_ALL_RULES_REQUEST"
export const GET_ALL_RULES_SUCCESS = "GET_ALL_RULES_SUCCESS"
export const GET_ALL_RULES_FAIL = "GET_ALL_RULES_FAIL"

export const GET_RULE_REQUEST = "GET_RULE_REQUEST"
export const GET_RULE_SUCCESS = "GET_RULE_SUCCESS"
export const GET_RULE_FAIL = "GET_RULE_FAIL"

