export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_SIGNOUT = 'USER_SIGNOUT';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const UPDATE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'DELETE_USER_FAIL';

export const GET_ROLE_USER_REQUEST = 'GET_ROLE_USER_REQUEST';
export const GET_ROLE_USER_SUCCESS = 'GET_ROLE_USER_SUCCESS';
export const GET_ROLE_USER_FAIL = 'GET_ROLE_USER_FAIL';